name: CI/CD for Go App on VPS

on:
  push:
    branches:
    - master
    paths:
    - 'golang/**'
  workflow_dispatch:

jobs:
  code-test:
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.0

      - name: Run Go tests
        run: |
          cd golang
          go test ./...

  build-and-push:
    needs: [code-test]
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Go image
        uses: docker/build-push-action@v2
        with:
          context: ./golang
          push: true
          tags: fitrinshl/sre-tech-assessment:golang
          platforms: linux/arm64,linux/amd64

  deploy:
    needs: [build-and-push]
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install kubectl
        uses: azure/setup-kubectl@v1

      - uses: azure/k8s-bake@v2
        with:
          renderEngine: 'helm'
          helmChart: './go-helm-chart/'
        id: bake

      - uses: Azure/k8s-deploy@v1.2
        with:
          action: deploy
          manifests: ${{ steps.bake.outputs.manifestsBundle }}