name: Deploy Node App to Minikube

on:
  workflow_run:
    workflows: [Test and Build Docker Images]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install kubectl
        uses: azure/setup-kubectl@v1

      - name: Start minikube (only for the first run)
        id: start_minikube
        uses: medyagh/setup-minikube@master

      - name: Cache Minikube state for future runs
        if: steps.start_minikube.outputs.first_run == 'true'
        uses: actions/cache@v2
        with:
          path: ${{ runner.user.dir }}/minikube
          key: minikube-state

      - name: Load Minikube state for subsequent runs
        if: steps.start_minikube.outputs.first_run == 'false'
        uses: actions/cache@v2
        with:
          path: ${{ runner.user.dir }}/minikube
          key: minikube-state
          
      - name: Run kubectl
        run: |
          minikube kubectl -- get pods

      - name: Apply manifest
        run: |
          kubectl apply -f ./manifest/nodejs-k8s.yaml
          kubectl get events

      - name: Check resources
        run: |
          minikube kubectl -- get pods
          minikube kubectl -- get svc

      - name: Test service URLs
        run: |
          curl $(minikube service node-service --url)