name: Deploy Node App to Minikube

on:
  workflow_run:
    workflows: [Test and Build Docker Images]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install kubectl
        uses: azure/setup-kubectl@v1

      - name: Start minikube
        uses: medyagh/setup-minikube@master

      - name: Run kubectl
        run: |
          minikube kubectl -- get pods

      - name: Apply manifest
        run: |
          kubectl apply -f ./manifest/nodejs-k8s.yaml -n default
      
      - name: Review logs
        run: |
          kubectl logs -l app=node-app

      # - name: Wait for rollout
      #   run: |
      #     kubectl rollout status deployment/node-app

      - name: Check resources
        run: |
          minikube kubectl -- get pods
          minikube kubectl -- get svc

      - name: Run app
        run: |
          curl $(minikube service node-service --url)