name: CI/CD for Go

on:
  push:
    branches:
    - master
    paths:
    - 'golang/**'

jobs:
  code-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.0

      - name: Run Go tests
        run: |
          cd golang
          go test ./...

  build-and-push:
    needs: [code-test]
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Go image
        uses: docker/build-push-action@v2
        with:
          context: ./golang
          push: true
          tags: fitrinshl/sre-tech-assessment:golang
          platforms: linux/arm64,linux/amd64

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install kubectl
        uses: azure/setup-kubectl@v1

      - name: Start minikube
        id: start_minikube
        uses: medyagh/setup-minikube@master

      - name: Run kubectl
        run: |
          minikube kubectl -- get pods --all-namespaces

      - name: Apply manifest
        run: |
          kubectl apply -f ./manifest/golang-k8s.yaml
      
      - name: Wait for pods to be running
        run: |
          while true; do
            RUNNING=$(kubectl get pods --field-selector=status.phase=Running --no-headers | wc -l)
            TOTAL=$(kubectl get pods --no-headers | wc -l)
            if [ "$RUNNING" -eq "$TOTAL" ]; then
              echo "All pods are running."
              break
            else
              echo "Not all pods are running. Waiting..."
              kubectl get pods
              kubectl get events
              sleep 20
            fi
          done

      - name: Check resources
        run: |
          minikube kubectl -- describe deployment/go-app
          minikube kubectl -- get svc

      - name: Test service URLs
        run: |
          curl $(minikube service go-service --url)