name: CI/CD for NodeJS App

on:
  push:
    branches:
    - master
    paths:
    - 'nodejs/**'
  workflow_dispatch:

jobs:
  code-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Use Node.js 21.6.2
        uses: actions/setup-node@v2
        with:
          node-version: 21.6.2

      - name: Install dependencies
        run: |
          cd nodejs
          npm ci
          
      - name: Run Node.js tests
        run: |
          cd nodejs
          npm test

  build-and-push:
    needs: [code-test]
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Node image
        run: |
          docker build -t fitrinshl/node-hello-world:latest ./nodejs
          docker push fitrinshl/node-hello-world:latest

  deploy:
    needs: [build-and-push]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install kubectl
        uses: azure/setup-kubectl@v1
      
      - name: Set Kubectl Context
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
          
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Render Helm chart
        uses: azure/k8s-bake@v2
        with:
          renderEngine: 'helm'
          helmChart: './node-helm-chart/'
        id: bake

      - name: Provision k8s resources
        uses: Azure/k8s-deploy@v1.2
        with:
          manifests: ${{ steps.bake.outputs.manifestsBundle }}