name: Test and Build Docker Images

on:
  push:
    branches:
      - master

jobs:
  golang-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.0

      - name: Run Go tests
        run: |
          cd golang
          go test ./...

  nodejs-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Use Node.js 21.6.2
        uses: actions/setup-node@v2
        with:
          node-version: 21.6.2

      - name: Install dependencies
        run: |
          cd nodejs
          npm ci
          
      - name: Run Node.js tests
        run: |
          cd nodejs
          npm test

  build-and-push:
    needs: [golang-test, nodejs-test]
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' &&
      paths:
        - 'golang/**'
        - 'nodejs/**'
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Go image
        uses: docker/build-push-action@v2
        with:
          context: ./golang
          push: true
          tags: fitrinshl/sre-tech-assessment:golang
          platforms: linux/arm64

      - name: Build and push Node image
        uses: docker/build-push-action@v2
        with:
          context: ./nodejs
          push: true
          tags: fitrinshl/sre-tech-assessment:nodejs
          platforms: linux/arm64